// <auto-generated />
using System;
using HelloMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloMvc.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20221115005922_seed_holiday_data")]
    partial class seed_holiday_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HelloMvc.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaysInOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndWorkingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartWorkingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HelloMvc.Models.Holiday", b =>
                {
                    b.Property<string>("HolidayCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("HolidayCode");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            HolidayCode = "NYD",
                            DisplayName = "New Year's Day"
                        },
                        new
                        {
                            HolidayCode = "MLKJD",
                            DisplayName = "Martin Luther King Jr. Day"
                        },
                        new
                        {
                            HolidayCode = "WB",
                            DisplayName = "Washington's Birthday"
                        },
                        new
                        {
                            HolidayCode = "MD",
                            DisplayName = "Memorial Day"
                        },
                        new
                        {
                            HolidayCode = "JTTH",
                            DisplayName = "Juneteenth"
                        },
                        new
                        {
                            HolidayCode = "ID",
                            DisplayName = "Independence Day"
                        },
                        new
                        {
                            HolidayCode = "LD",
                            DisplayName = "Labor Day"
                        },
                        new
                        {
                            HolidayCode = "CD",
                            DisplayName = "Columbus Day"
                        },
                        new
                        {
                            HolidayCode = "VD",
                            DisplayName = "Veterans Day"
                        },
                        new
                        {
                            HolidayCode = "TG",
                            DisplayName = "Thanksgiving"
                        },
                        new
                        {
                            HolidayCode = "CM",
                            DisplayName = "Christmas"
                        });
                });

            modelBuilder.Entity("HelloMvc.Models.Vacation", b =>
                {
                    b.Property<int>("VacationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacationId"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VacationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("HelloMvc.Models.Vacation", b =>
                {
                    b.HasOne("HelloMvc.Models.Employee", "Employee")
                        .WithMany("Vacations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HelloMvc.Models.Employee", b =>
                {
                    b.Navigation("Vacations");
                });
#pragma warning restore 612, 618
        }
    }
}
